- id: automation_theme_light_sun_dawn
  alias: Set Lighting to Dusk/Dawn
  trigger:
  - above: '3'
    below: '10'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: input_select.current_light_profile
      option: dawn_dusk
    service: input_select.select_option
- id: automation_theme_light_sun_candlelight
  alias: Set Lighting to Candlelight
  trigger:
  - below: '-10'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: input_select.current_light_profile
      option: candlelight
    service: input_select.select_option
- id: automation_theme_light_sun_incandescent
  alias: Set Lighting to Incandescent
  trigger:
  - above: '-10'
    below: '-3'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: input_select.current_light_profile
      option: incandescent
    service: input_select.select_option
- id: automation_theme_light_sun_sunrise
  alias: Set Lighting to Sunrise/Sunset
  trigger:
  - above: '-3'
    below: '3'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: input_select.current_light_profile
      option: sunrise_sunset
    service: input_select.select_option
- id: automation_theme_light_sun_dawn
  alias: Set Lighting to Dusk/Dawn
  trigger:
  - above: '3'
    below: '10'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: input_select.current_light_profile
      option: dawn_dusk
    service: input_select.select_option
- id: automation_theme_light_sun_sunny
  alias: Set Lighting to Sunny
  trigger:
  - above: '10'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data:
      entity_id: input_select.current_light_profile
      option: sunny_noon
    service: input_select.select_option
- id: set_active_light_profile
  alias: Set Active Lights to New Profile
  trigger:
  - entity_id: input_select.current_light_profile
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: '{{ states.light | selectattr("state", "equalto", "on") | map(attribute="entity_id") | join(", ") }}'
      profile: '{{ states.input_select.current_light_profile.state }}'
      transition: 120
    service: light.turn_on
- id: '1535944998290'
  alias: Set New Light to Active Profile
  trigger:
  - platform: template
    value_template: '{{ states.light | selectattr("state", "equalto", "on") }}'
  condition:
  - condition: template
    value_template: '{{ is_state(trigger.to_state.entity_id, "on") }}'
  action:
  - data: {}
    data_template:
      entity_id: '{{ trigger.to_state.entity_id }}'
      profile: '{{ states.input_select.current_light_profile.state }}'
      transition: 120
    service: light.turn_on
