- platform: denonavr
  #  host: 192.168.1.196

- platform: samsungtv
  host: 192.168.1.253
  port: 8001

- platform: pioneer
  host: 192.168.1.217
  name: pioneer_avr
#- platform: plex
#  entity_namespace: 'plex'
#  use_episode_art: true

#- platform: pioneer
#  host: 192.168.1.217
